import 'controller/logout_modal_controller.dart';import 'package:flutter/material.dart';import 'package:ticktter/core/app_export.dart';import 'package:ticktter/widgets/custom_button.dart';
// ignore_for_file: must_be_immutable
class LogoutModalBottomsheet extends StatelessWidget {LogoutModalBottomsheet(this.controller);

LogoutModalController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.infinity, decoration: AppDecoration.outlineGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 24, top: 8, right: 24), child: CommonImageView(svgPath: ImageConstant.imgFrame, height: getVerticalSize(3.00), width: getHorizontalSize(38.00))), Padding(padding: getPadding(left: 24, top: 27, right: 24), child: Text("lbl_logout".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold24RedA200)), Container(height: getVerticalSize(1.00), width: getHorizontalSize(380.00), margin: getMargin(left: 24, top: 20, right: 24), decoration: BoxDecoration(color: ColorConstant.gray200)), Padding(padding: getPadding(left: 24, top: 25, right: 24), child: Text("msg_are_you_sure_yo".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold20Gray800)), Padding(padding: getPadding(left: 24, top: 22, right: 24, bottom: 48), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.max, children: [CustomButton(width: 184, text: "lbl_cancel".tr, variant: ButtonVariant.FillDeeporange50, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingAll18, fontStyle: ButtonFontStyle.UrbanistRomanBold16DeeporangeA401, onTap: onTapCancel), CustomButton(width: 184, text: "lbl_yes_logout".tr, margin: getMargin(left: 12), variant: ButtonVariant.OutlineDeeporangeA40035_1, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingAll18, fontStyle: ButtonFontStyle.UrbanistRomanBold16)]))]))); } 
onTapCancel() { Get.back(); } 
 }
